# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e29eaa4a0c768338233157c4cf5d6a1f8eb0b8345ac62dd7919397f82514d494c4c91fd0d1f0fb412a72e7afe327ca4a63b733e301f800cd60f6f6b1ad469a74

test:
  secret_key_base: 9f8dcf5e51388af222823dd843513fc1f0a607545c569c4f5b10dc9e4f9d91dedac220725518821347c7b9e7f3abc3654982de57a03d952897294f95d238045e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
